title: george-were
theme: jekyll-theme-hacker

host: 0.0.0.0

url: "https://georgewere.github.io/"

encoding: UTF-8

plugins:
  - jekyll-sitemap

index_menu: [[ghost, ghost], [pppD, pppd]]


htb_chls: [
  [for, Forensics],
  [mob, Mobile],
  [pwn, Pwn],
  [web, Web]
]

htb_menu: [[14, AI], [2, RE], [3, JSON], [4, Zetta], [1, Blame]]

malware_menu: [[1, Setting Up malware Analysis Lab]]
